//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.GolesPorJugadorEquipo = new HashSet<GolesPorJugadorEquipo>();
        }
    
        public int idJugador { get; set; }

        [Required(ErrorMessage = "¡El nombre es obligatorio!")]
        [StringLength(80, ErrorMessage = "El nombre debe estar entre 3 y 80 caracteres", MinimumLength = 3)]
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GolesPorJugadorEquipo> GolesPorJugadorEquipo { get; set; }
    }
}
